In [1]:
import os
os.chdir('C:\\Users\\QTP864\\Python\\atp-world-tour-tennis-data\\')
os.getcwd()

'C:\\Users\\QTP864\\Python\\atp-world-tour-tennis-data'

In [2]:
import pandas as pd

# Import data

In [3]:
# Function to import <2017 data and append 2017 data
def import_tennisdata(pf_data, pf_header, pf_data_2017=None):
    # Import column titles as list
    header_txt = pf_header
    with open(pf_header, "r") as f:
        pf_header = f.readlines()
        pf_header = [header.rstrip("\n") for header in pf_header]
    
    # Import <2017 data into dataframe
    df = pd.read_csv(pf_data, names = pf_header)
    
    # Import and append 2017 data
    if pf_data_2017 is not None:
        df_2017 = pd.read_csv(pf_data_2017, names = pf_header)
        df = df.append(df_2017)
    
    return df

In [4]:
header = "csv\\3_match_stats\\match_stats_column_titles.txt"
data = "csv\\3_match_stats\\match_stats_1991-2016_UNINDEXED.csv"
data_2017 = "csv\\3_match_stats\\match_stats_2017_UNINDEXED.csv"
match_stats = import_tennisdata(data, header, data_2017)

match_stats.head()

,tourney_order,match_id,match_stats_url_suffix,match_time,match_duration,winner_aces,winner_double_faults,winner_first_serves_in,winner_first_serves_total,winner_first_serve_points_won,...,loser_second_serve_return_won,loser_second_serve_return_total,loser_break_points_converted,loser_break_points_return_total,loser_service_games_played,loser_return_games_played,loser_return_points_won,loser_return_points_total,loser_total_points_won,loser_total_points_total
0,0,1991-7308-k181-l206,/en/scores/1991/7308/MS002/match-stats,01:20:00,80.0,3.0,0.0,0.0,65.0,29.0,...,7.0,19.0,2.0,2.0,11.0,11.0,24.0,65.0,61.0,134.0
1,0,1991-7308-k181-s351,/en/scores/1991/7308/MS001/match-stats,01:29:00,89.0,1.0,2.0,44.0,65.0,31.0,...,9.0,21.0,3.0,5.0,12.0,12.0,22.0,65.0,68.0,148.0
2,0,1991-7308-k181-s424,/en/scores/1991/7308/MS005/match-stats,00:55:00,55.0,0.0,1.0,17.0,36.0,11.0,...,6.0,19.0,2.0,3.0,8.0,7.0,12.0,36.0,32.0,90.0
3,0,1991-7308-a031-s331,/en/scores/1991/7308/MS013/match-stats,01:09:00,69.0,2.0,3.0,44.0,58.0,28.0,...,7.0,14.0,2.0,8.0,9.0,9.0,23.0,58.0,52.0,114.0
4,0,1991-7308-k030-w136,/en/scores/1991/7308/MS009/match-stats,01:29:00,89.0,6.0,3.0,37.0,71.0,25.0,...,15.0,34.0,2.0,3.0,10.0,10.0,27.0,71.0,59.0,135.0

In [5]:
header = "csv\\2_match_scores\\match_scores_column_titles.txt"
data = "csv\\2_match_scores\\match_scores_1991-2016_UNINDEXED.csv"
data_2017 = "csv\\2_match_scores\\match_scores_2017_UNINDEXED.csv"
match_scores = import_tennisdata(data, header, data_2017)

match_scores.tail()

,tourney_year_id,tourney_order,tourney_slug,tourney_url_suffix,tourney_round_name,round_order,match_order,winner_name,winner_player_id,winner_slug,...,loser_seed,match_score_tiebreaks,winner_sets_won,loser_sets_won,winner_games_won,loser_games_won,winner_tiebreaks_won,loser_tiebreaks_won,match_id,match_stats_url_suffix
3825,2017-605,67,nitto-atp-finals,/en/scores/current/nitto-atp-finals/605/results,Round Robin,3,8,Dominic Thiem,tb69,dominic-thiem,...,Alt,63 36 64,2,1,15,13,0,0,results-605-tb69-cd85,/en/scores/2017/605/MS008/match-stats
3826,2017-605,67,nitto-atp-finals,/en/scores/current/nitto-atp-finals/605/results,Round Robin,3,9,Jack Sock,sm25,jack-sock,...,5,57 62 76(4),2,1,18,15,1,0,results-605-sm25-c977,/en/scores/2017/605/MS021/match-stats
3827,2017-605,67,nitto-atp-finals,/en/scores/current/nitto-atp-finals/605/results,Round Robin,3,10,Grigor Dimitrov,d875,grigor-dimitrov,...,Alt,61 61,2,0,12,2,0,0,results-605-d875-cd85,/en/scores/2017/605/MS009/match-stats
3828,2017-605,67,nitto-atp-finals,/en/scores/current/nitto-atp-finals/605/results,Round Robin,3,11,Grigor Dimitrov,d875,grigor-dimitrov,...,7,60 62,2,0,12,2,0,0,results-605-d875-gb88,/en/scores/2017/605/MS013/match-stats
3829,2017-605,67,nitto-atp-finals,/en/scores/current/nitto-atp-finals/605/results,Round Robin,3,12,David Goffin,gb88,david-goffin,...,NaN,76(5) 67(4) 64,2,1,19,17,1,1,results-605-gb88-n409,/en/scores/2017/605/MS010/match-stats

In [7]:
header = "csv\\5_players\\player_overviews_column_titles.txt"
data = "csv\\5_players\\player_overviews_UNINDEXED.csv"
player_data = import_tennisdata(data, header)

player_data.tail()

,player_id,player_slug,first_name,last_name,player_url,flag_code,residence,birthplace,birthdate,birth_year,birth_month,birth_day,turned_pro,weight_lbs,weight_kg,height_ft,height_inches,height_cm,handedness,backhand
10907,z435,a-zorab,A.,Zorab,http://www.atpworldtour.com/en/players/a-zorab...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10908,z437,j-zimmermann,J.,Zimmermann,http://www.atpworldtour.com/en/players/j-zimme...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10909,z436,g-zinn,G.,Zinn,http://www.atpworldtour.com/en/players/g-zinn/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10910,z440,c-zenger,C.,Zenger,http://www.atpworldtour.com/en/players/c-zenge...,GER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10911,z442,a-ziffo,A.,Ziffo,http://www.atpworldtour.com/en/players/a-ziffo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
player_data = player_data.dropna(axis=0, subset=["birthdate"])
player_data.tail()

,player_id,player_slug,first_name,last_name,player_url,flag_code,residence,birthplace,birthdate,birth_year,birth_month,birth_day,turned_pro,weight_lbs,weight_kg,height_ft,height_inches,height_cm,handedness,backhand
10892,z412,zhicheng-zhu,Zhicheng,Zhu,http://www.atpworldtour.com/en/players/zhichen...,CHN,NaN,NaN,1995.09.14,1995.0,9.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,Right-Handed,Two-Handed Backhand
10894,z413,jiacheng-zhu,Jiacheng,Zhu,http://www.atpworldtour.com/en/players/jiachen...,CHN,NaN,NaN,1996.09.30,1996.0,9.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10898,z419,bernabe-zapata-miralles,Bernabe,Zapata Miralles,http://www.atpworldtour.com/en/players/bernabe...,ESP,"Valencia, Spain","Valencia, Spain",1997.01.12,1997.0,1.0,12.0,NaN,161.0,73.0,"6'1""",73.0,185.0,Right-Handed,Two-Handed Backhand
10903,z432,augustos-zerlendis,Augustos,Zerlendis,http://www.atpworldtour.com/en/players/augusto...,GRE,NaN,NaN,1886.11.05,1886.0,11.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10904,z434,ladislav-zemla,Ladislav,Zemla,http://www.atpworldtour.com/en/players/ladisla...,CZE,NaN,NaN,1887.11.06,1887.0,11.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
header = "csv\\4_rankings\\rankings_column_titles.txt"
data = "csv\\4_rankings\\rankings_2016.csv"
rankings = import_tennisdata(data, header)

rankings

,week_title,week_year,week_month,week_day,rank_text,rank_number,move_positions,move_direction,player_age,ranking_points,tourneys_played,player_url,player_slug,player_id
0,2016.12.26,2016,12,26,1,1,NaN,NaN,29.0,12410,16,/en/players/andy-murray/mc10/overview,andy-murray,mc10
1,2016.12.26,2016,12,26,2,2,NaN,NaN,29.0,11780,17,/en/players/novak-djokovic/d643/overview,novak-djokovic,d643
2,2016.12.26,2016,12,26,3,3,NaN,NaN,25.0,5450,19,/en/players/milos-raonic/r975/overview,milos-raonic,r975
3,2016.12.26,2016,12,26,4,4,NaN,NaN,31.0,5315,21,/en/players/stan-wawrinka/w367/overview,stan-wawrinka,w367
4,2016.12.26,2016,12,26,5,5,NaN,NaN,26.0,4905,20,/en/players/kei-nishikori/n552/overview,kei-nishikori,n552
5,2016.12.26,2016,12,26,6,6,NaN,NaN,28.0,3650,22,/en/players/marin-cilic/c977/overview,marin-cilic,c977
6,2016.12.26,2016,12,26,7,7,NaN,NaN,30.0,3625,18,/en/players/gael-monfils/mc65/overview,gael-monfils,mc65
7,2016.12.26,2016,12,26,8,8,NaN,NaN,23.0,3415,28,/en/players/dominic-thiem/tb69/overview,dominic-thiem,tb69
8,2016.12.26,2016,12,26,9,9,NaN,NaN,30.0,3300,16,/en/players/rafael-nadal/n409/overview,rafael-nadal,n409
9,2016.12.26,2016,12,26,10,10,NaN,NaN,31.0,3060,21,/en/players/tomas-berdych/ba47/overview,tomas-berdych,ba47
10,2016.12.26,2016,12,26,11,11,NaN,NaN,26.0,2750,24,/en/players/david-goffin/gb88/overview,david-goffin,gb88
11,2016.12.26,2016,12,26,12,12,NaN,NaN,31.0,2550,17,/en/players/jo-wilfried-tsonga/t786/overview,jo-wilfried-tsonga,t786
12,2016.12.26,2016,12,26,13,13,NaN,NaN,21.0,2460,20,/en/players/nick-kyrgios/ke17/overview,nick-kyrgios,ke17
13,2016.12.26,2016,12,26,14,14,NaN,NaN,28.0,2350,25,/en/players/roberto-bautista%20agut/bd06/overview,roberto-bautista%20agut,bd06
14,2016.12.26,2016,12,26,15,15,NaN,NaN,22.0,2156,24,/en/players/lucas-pouille/pf39/overview,lucas-pouille,pf39
15,2016.12.26,2016,12,26,16,16,NaN,NaN,35.0,2130,15,/en/players/roger-federer/f324/overview,roger-federer,f324
16,2016.12.26,2016,12,26,17,17,NaN,NaN,25.0,2035,25,/en/players/grigor-dimitrov/d875/overview,grigor-dimitrov,d875
17,2016.12.26,2016,12,26,18,18,NaN,NaN,30.0,1885,20,/en/players/richard-gasquet/g628/overview,richard-gasquet,g628
18,2016.12.26,2016,12,26,19,19,NaN,NaN,31.0,1850,21,/en/players/john-isner/i186/overview,john-isner,i186
19,2016.12.26,2016,12,26,20,20,NaN,NaN,37.0,1795,24,/en/players/ivo-karlovic/k336/overview,ivo-karlovic,k336
20,2016.12.26,2016,12,26,21,21,NaN,NaN,34.0,1785,22,/en/players/david-ferrer/f401/overview,david-ferrer,f401
21,2016.12.26,2016,12,26,22,22,NaN,NaN,30.0,1780,25,/en/players/pablo-cuevas/c882/overview,pablo-cuevas,c882
22,2016.12.26,2016,12,26,23,23,NaN,NaN,24.0,1710,19,/en/players/jack-sock/sm25/overview,jack-sock,sm25
23,2016.12.26,2016,12,26,24,24,NaN,NaN,19.0,1655,24,/en/players/alexander-zverev/z355/overview,alexander-zverev,z355
24,2016.12.26,2016,12,26,25,25,NaN,NaN,31.0,1585,25,/en/players/gilles-simon/sd32/overview,gilles-simon,sd32
25,2016.12.26,2016,12,26,26,26,NaN,NaN,24.0,1465,25,/en/players/bernard-tomic/ta46/overview,bernard-tomic,ta46
26,2016.12.26,2016,12,26,27,27,NaN,NaN,28.0,1435,32,/en/players/albert-ramos-vinolas/r772/overview,albert-ramos-vinolas,r772
27,2016.12.26,2016,12,26,28,28,NaN,NaN,35.0,1410,25,/en/players/feliciano-lopez/l397/overview,feliciano-lopez,l397
28,2016.12.26,2016,12,26,29,29,NaN,NaN,30.0,1385,28,/en/players/viktor-troicki/t840/overview,viktor-troicki,t840
29,2016.12.26,2016,12,26,30,30,NaN,NaN,25.0,1370,28,/en/players/pablo-carreno%20busta/cd85/overview,pablo-carreno%20busta,cd85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99575,2016.01.04,2016,1,4,2220T,2220,NaN,NaN,19.0,1,7,/en/players/ku%20keon-kang/ke45/overview,ku%20keon-kang,ke45
99576,2016.01.04,2016,1,4,2220T,2220,NaN,NaN,22.0,1,7,/en/players/punnakrit-kritakara/bk41/overview,punnakrit-kritakara,bk41
99577,2016.01.04,2016,1,4,2220T,2220,NaN,NaN,22.0,1,7,/en/players/francesco-moncagatto/mj45/overview,francesco-moncagatto,mj45
99578,2016.01.04,2016,1,4,2220T,2220,NaN,NaN,17.0,1,7,/en/players/gian%20marco-moroni/mp83/overview,gian%20marco-moroni,mp83
99579,2016.01.04,2016,1,4,2220T,2220,NaN,NaN,21.0,1,7,/en/players/herkko-pollanen/pf69/overview,herkko-pollanen,pf69
99580,2016.01.04,2016,1,4,2220T,2220,NaN,NaN,19.0,1,7,/en/players/alexey-prokopchuk/pm34/overview,alexey-prokopchuk,pm34
99581,2016.01.04,2016,1,4,2220T,2220,NaN,NaN,24.0,1,7,/en/players/alberto-sibona/sl05/overview,alberto-sibona,sl05
99582,2016.01.04,2016,1,4,2220T,2220,NaN,NaN,22.0,1,7,/en/players/chaleechan-tanasugarn/tb71/overview,chaleechan-tanasugarn,tb71
99583,2016.01.04,2016,1,4,2234T,2234,NaN,NaN,21.0,1,8,/en/players/zhao-cai/cf05/overview,zhao-cai,cf05
99584,2016.01.04,2016,1,4,2234T,2234,NaN,NaN,21.0,1,8,/en/players/durukan-durmus/da42/overview,durukan-durmus,da42
99585,2016.01.04,2016,1,4,2234T,2234,NaN,NaN,24.0,1,8,/en/players/vasil-shandarov/sk77/overview,vasil-shandarov,sk77
99586,2016.01.04,2016,1,4,2234T,2234,NaN,NaN,19.0,1,8,/en/players/keivon-tabrizi/te23/overview,keivon-tabrizi,te23
99587,2016.01.04,2016,1,4,2238T,2238,NaN,NaN,23.0,1,9,/en/players/jatin-dahiya/db33/overview,jatin-dahiya,db33
99588,2016.01.04,2016,1,4,2238T,2238,NaN,NaN,22.0,1,9,/en/players/oliver-hudson/ha87/overview,oliver-hudson,ha87
99589,2016.01.04,2016,1,4,2238T,2238,NaN,NaN,24.0,1,9,/en/players/isade-juneau/j525/overview,isade-juneau,j525
99590,2016.01.04,2016,1,4,2238T,2238,NaN,NaN,19.0,1,9,/en/players/alexander-klintcharov/kg53/overview,alexander-klintcharov,kg53
99591,2016.01.04,2016,1,4,2238T,2238,NaN,NaN,20.0,1,9,/en/players/harrison-lombe/le15/overview,harrison-lombe,le15
99592,2016.01.04,2016,1,4,2238T,2238,NaN,NaN,19.0,1,9,/en/players/mitchell%20william-robins/rh43/ove...,mitchell%20william-robins,rh43
99593,2016.01.04,2016,1,4,2238T,2238,NaN,NaN,20.0,1,9,/en/players/jonas-trinker/tc87/overview,jonas-trinker,tc87
99594,2016.01.04,2016,1,4,2245T,2245,NaN,NaN,20.0,1,10,/en/players/yuri-andrade/ab91/overview,yuri-andrade,ab91
99595,2016.01.04,2016,1,4,2245T,2245,NaN,NaN,20.0,1,10,/en/players/ren-nakamura/n786/overview,ren-nakamura,n786
99596,2016.01.04,2016,1,4,2247T,2247,NaN,NaN,24.0,1,11,/en/players/sagar-ahuja/ac05/overview,sagar-ahuja,ac05
99597,2016.01.04,2016,1,4,2247T,2247,NaN,NaN,18.0,1,11,/en/players/edan-bakshi/bl45/overview,edan-bakshi,bl45
99598,2016.01.04,2016,1,4,2247T,2247,NaN,NaN,18.0,1,11,/en/players/joseph-guillin/gh32/overview,joseph-guillin,gh32
99599,2016.01.04,2016,1,4,2247T,2247,NaN,NaN,26.0,1,11,/en/players/lofo-ramiaramanana/r964/overview,lofo-ramiaramanana,r964
99600,2016.01.04,2016,1,4,2247T,2247,NaN,NaN,21.0,1,11,/en/players/ferdun-shevkedov/so97/overview,ferdun-shevkedov,so97
99601,2016.01.04,2016,1,4,2247T,2247,NaN,NaN,21.0,1,11,/en/players/mousa%20shanan-zayed/z367/overview,mousa%20shanan-zayed,z367
99602,2016.01.04,2016,1,4,2253,2253,NaN,NaN,19.0,1,12,/en/players/juan-montes/mp33/overview,juan-montes,mp33
99603,2016.01.04,2016,1,4,2254,2254,NaN,NaN,21.0,1,13,/en/players/mostafa-hatem/mp39/overview,mostafa-hatem,mp39
99604,2016.01.04,2016,1,4,2255,2255,NaN,NaN,27.0,1,16,/en/players/tinotenda-chanakira/cb56/overview,tinotenda-chanakira,cb56

In [32]:
match_stats.columns

Index(['tourney_order', 'match_id', 'match_stats_url_suffix', 'match_time',
       'match_duration', 'winner_aces', 'winner_double_faults',
       'winner_first_serves_in', 'winner_first_serves_total',
       'winner_first_serve_points_won', 'winner_first_serve_points_total',
       'winner_second_serve_points_won', 'winner_second_serve_points_total',
       'winner_break_points_saved', 'winner_break_points_serve_total',
       'winner_service_points_won', 'winner_service_points_total',
       'winner_first_serve_return_won', 'winner_first_serve_return_total',
       'winner_second_serve_return_won', 'winner_second_serve_return_total',
       'winner_break_points_converted', 'winner_break_points_return_total',
       'winner_service_games_played', 'winner_return_games_played',
       'winner_return_points_won', 'winner_return_points_total',
       'winner_total_points_won', 'winner_total_points_total', 'loser_aces',
       'loser_double_faults', 'loser_first_serves_in',
       'loser_first_serves_total', 'loser_first_serve_points_won',
       'loser_first_serve_points_total', 'loser_second_serve_points_won',
       'loser_second_serve_points_total', 'loser_break_points_saved',
       'loser_break_points_serve_total', 'loser_service_points_won',
       'loser_service_points_total', 'loser_first_serve_return_won',
       'loser_first_serve_return_total', 'loser_second_serve_return_won',
       'loser_second_serve_return_total', 'loser_break_points_converted',
       'loser_break_points_return_total', 'loser_service_games_played',
       'loser_return_games_played', 'loser_return_points_won',
       'loser_return_points_total', 'loser_total_points_won',
       'loser_total_points_total'],
      dtype='object')

# Merge data

In [ ]:
match_data = pd.merge(match_stats, match_scores, how="inner", on="match_id", suffixes=("", "_y"))
#Remove duplicate columns
col_to_delete = [col for col in match_data.columns if '_y' in col]
match_data.drop(labels=col_to_delete, axis=1, inplace=True)
match_data.columns

In [ ]:
match_data.tail()

In [ ]:
match_data.shape

In [ ]:
#Drop duplicate rows
match_data.drop_duplicates(subset="match_stats_url_suffix", inplace=True)
match_data.shape

# Extract some stats

### Extract win ratio per player

In [ ]:
#Calculate win ratio per player
wins = match_data["winner_name"].value_counts()

losses = match_data["loser_name"].value_counts()
total_matches = wins + losses
#Keep only players with matches > 50 and drop NaN's
total_matches = total_matches[total_matches > 50].dropna()
win_ratio = wins / (total_matches)
win_ratio = win_ratio.dropna()

In [ ]:
win_ratio.sort_values(ascending=False)

### Extract yearly win ratio per player and plot

In [ ]:
match_data["year"] = match_data["match_id"].apply(lambda x: str(x)[0:4])

In [ ]:
win_count = match_data.groupby(by=["winner_name", "year"]).count()
win_count = win_count["match_id"].unstack()
loss_count = match_data.groupby(by=["loser_name", "year"]).count()
loss_count = loss_count["match_id"].unstack()
win_ratio_yearly = win_count/(loss_count + win_count)
win_ratio_yearly

In [ ]:
win_ratio_yearly.loc["Roger Federer"]

In [ ]:
#Plot the win/loss data for certain players -- barchart
import matplotlib.pyplot as plt
from numpy import arange

fig = plt.figure(figsize=(16,10))
ax = fig.add_subplot(1,1,1)
players = ["Roger Federer", "Rafael Nadal", "Novak Djokovic"]
x_offset = -0.2
for player in players:
    ax.bar(height=win_count.loc[player],
           x=arange(len(win_count.loc[player]))-x_offset,
           width=0.2,
           align="center",
           edgecolor="black",
           linewidth=0.1
           )
    x_offset += 0.2
    
xlabels = win_count.columns
ax.set_xticks(range(0, len(xlabels)))
ax.set_xticklabels(xlabels, rotation = 45, size=14)
ax.set_xlim(left=(1997-1991))
plt.show()

In [ ]:
#Plot the win/loss data for certain players -- lineplot
import matplotlib.pyplot as plt
from numpy import arange

fig = plt.figure(figsize=(16,14))
players = ["Roger Federer", "Rafael Nadal", "Novak Djokovic"]
colors = ["red", "#f4c441", "#41a3f4"]

ax1 = fig.add_subplot(3,1,1)
for i, player in enumerate(players):
    ax1.plot(win_count.loc[player],
            color=colors[i],
           linewidth=2,
           dashes=(3,2),
           marker="o")

ax2 = fig.add_subplot(3,1,2)
for i, player in enumerate(players):
    ax2.plot(loss_count.loc[player],
            color=colors[i],
           linewidth=2,
           dashes=(3,2),
           marker="o")    
    
ax3 = fig.add_subplot(3,1,3)
for i, player in enumerate(players):
    ax3.plot(win_ratio_yearly.loc[player],
            color=colors[i],
           linewidth=2,
           dashes=(3,2),
           marker="o")    
    
xlabels = win_count.columns

axes = [ax1, ax2]
for ax in axes:
    ax.set_xticks(range(0, len(xlabels)))
    ax.set_xlim(left=(1997-1991))
    ax.set_ylim(bottom=0, top=100)
    ax.tick_params(labelsize=14)
    ax.grid(b=True, color="#d9d9d9", linewidth=1.5)
    ax.set_xticklabels([])
    
ax3.set_xticklabels(xlabels, rotation = 45)
ax3.tick_params(labelsize=14)
ax3.grid(b=True, color="#d9d9d9", linewidth=1.5)
ax3.set_xlim(left=(1997-1991))
ax3.set_ylim(0.2, 1)

ax2.set_ylim(0,30)

ax1.set_title("Wins", size=20, fontweight="bold")
ax2.set_title("Losses", size=20, fontweight="bold")
ax3.set_title("Win ratio", size=20, fontweight="bold")
ax1.legend(loc="upper left", fontsize="x-large")
plt.show()

In [ ]:
#Plot the win ratio since start career for certain players

# Extract tiebreaks stats per player

In [ ]:
#Group tiebreak wins and losses for each winner of the match
winner_tb = match_data.groupby(by=["winner_name"]).sum()
winner_tb = winner_tb[["winner_tiebreaks_won", "loser_tiebreaks_won"]]

#Group tiebreak wins and losses for each winner of the match
loser_tb = match_data.groupby(by=["loser_name"]).sum()
loser_tb = loser_tb[["winner_tiebreaks_won", "loser_tiebreaks_won"]]

#Sum up data to get total wins/losses per player
tb_data2 = pd.DataFrame(index=winner_tb.index)
tb_data2["tiebreaks_won"] = winner_tb["winner_tiebreaks_won"] + loser_tb["loser_tiebreaks_won"]
tb_data2["tiebreaks_lost"] = winner_tb["loser_tiebreaks_won"] + loser_tb["winner_tiebreaks_won"]
#Create column with win ratio
tb_data2["win_ratio"] = tb_data2["tiebreaks_won"]/(tb_data2["tiebreaks_won"]+tb_data2["tiebreaks_lost"])

tb_data_elite = tb_data2[tb_data2["tiebreaks_won"] >= 50]
tb_data_elite.sort_values("win_ratio", ascending=False)

In [ ]:
"""
SLOW METHOD OF EXTRACTING TIEBREAK DATA PER PLAYER

#Create dataframe with players > 50 matches
cols = ["tiebreaks_won", "tiebreaks_lost"]
tb_data = pd.DataFrame(columns = cols, index = win_ratio.keys())
tb_data[["tiebreaks_won", "tiebreaks_lost"]] = 0

#Fill in tiebreak wins and losses data in dataframe
for index, row in match_data.iterrows():
    winner = row["winner_name"]
    w_tb_won = row["winner_tiebreaks_won"]
    w_tb_lost = row["loser_tiebreaks_won"]
    loser = row["loser_name"]
    l_tb_won = row["loser_tiebreaks_won"]
    l_tb_lost = row["winner_tiebreaks_won"]
    
    if winner in tb_data.index:
        tb_data.loc[winner]["tiebreaks_won"] += w_tb_won
        tb_data.loc[winner]["tiebreaks_lost"] += w_tb_lost

    if loser in tb_data.index:
        tb_data.loc[loser]["tiebreaks_won"] += l_tb_won
        tb_data.loc[loser]["tiebreaks_lost"] += l_tb_lost
        
#Create column with win ratio
tb_data["win_ratio"] = tb_data["tiebreaks_won"]/(tb_data["tiebreaks_won"] + tb_data["tiebreaks_lost"])

"""